### ISSUE TITLE
Sign up (via email and google)

### ISSUE THREAD

**Issue by adzamkomladev** [Oaks-Africa/oak#1]
### Details:
Sign-up is collecting preliminary data about the user for authentication, including the email, password, and name. Data to be collected include First Name, Last Name, Email Address, Password and Confirm Password. Users can sign up with their google account. Type of users to sign up include only Clients (Estate owners, tenants/customers, employees, developers)

### Instructions (frontend)

- Use Taiga UI form controls
- Use Akita Store
- Use EventEmitter
- Use Typed Reactive forms
- Use Apollo client for GraphQL requests
- Use interfaces for request body and data shapes
- Arrange form neatly
- Use alerts/error helpers to display errors
- Mobile responsive

### Tasks Breakdown

- [ ] Create sign up form component
- [ ] Create sign up page component
- [ ] Emit form submitted event from sign up form component
- [ ] Receive auth state data into sign up form component
- [ ] Call signUpViaEmail / signUpViaGoogle graphql endpoints
- [ ] Handle errors from backend services
- [ ] Make UI/UX pleasing
- [ ] Make UI mobile responsive
- [ ] Refactor to remove redundant code
- [ ] Attempt testing code
- [ ] Create signUpViaEmail GraphQL endpoint
- [ ] Create signUpViaGoogle GraphQL endpoint
- [ ] Create User Created workflow
- [ ] Send Welcome Email notification

Notifications?
Yes (Welcome email)

Ui avatars to generate avatars for the first time.....https://ui-avatars.com/api/?name=John+Doe

Flow:

#### General flow
```mermaid
sequenceDiagram
	autonumber;
	participant O as Oaks Platform
	participant A as oaks.gateways.users
	participant B as oaks.services.users

	O ->> A: GraphQL signUpViaEmail/signUpViaGoogle
	A->>B: rpc.CreateUser(userDetails)
	Note over A, B: Create User with details provided
	B-->>A: User
	Note over A, B: Returns created User

	A -->> O: User
```

#### User-created workflow
```mermaid
sequenceDiagram
	autonumber;
	participant A as oaks.services.users
        participant B as kafka
        participant C as oaks.services.notifications
        participant D as User's mailbox

	A->>B: publish oaks.users.user.created
	Note over A, B: Publish kafka event for when users is created
	B-->>C: User
	Note over B, C: event is consumed from kafka by C
        C-->>D: Sends email to user
```

#### Frontend flow
```mermaid
sequenceDiagram
	autonumber;
	participant A as Sign Up Form component
        participant B as Sign Up Page
        participant C as oaks.gateways.users
        participant D as AuthStore (Akita)

	A->>B: formData.emit()
	Note over A, B: Emit form data to Sign Up Page after user clicks on submit
	B-->>C: AuthService.signUpViaEmail() / AuthService.signUpViaGoogle()
	Note over B, C: form data is sent to oaks.gateways.users endpoint via the AuthService functions
        C-->>D: AuthStore.updateAuthState() (Akita)
        Note over C,D: response is then used to update AuthState in AuthStore
        D-->>A: emit AuthState
        Note over A,D: AuthState is then emited via a subscribed observable in A to give response on whether sign up was succsessful
```
