### ISSUE TITLE
2fa

### ISSUE THREAD

**Issue by adzamkomladev** [Oaks-Africa/oak#27]
### Details:
2fa is responsible for making sure a user is the right user making certain actions.  This usually means sending a 6-digit code to their emails or phone numbers and making sure said code is entered and validated before they are allowed access to whatever functionality is being blocked by the 2fa.

We need UI that will allow users to send code and enter the code for validation, backend functionality that will send and verify the code before allowing users to continue with whatever functionality they want to perform, etc.

### Instructions (frontend)

- Use Taiga UI form controls
- Use Akita Store
- Use EventEmitter
- Use Typed Reactive forms
- Use Apollo client for GraphQL requests
- Use interfaces for request body and data shapes
- Arrange form neatly
- Use alerts/error helpers to display errors
- Mobile responsive

### Tasks Breakdown

- [ ] Create 2fa modal
- [ ] Create otp code input form component with submission
- [ ] Request otp code from backend
- [ ] Verify otp code from backend
- [ ] Add live timer component for otp code expiration
- [ ] show error (alerts in 2fa modal component)
- [ ] Send otp endpoint
- [ ] Verify otp endpoint
- [ ] Send notification via notifications service
- [ ] Make 2fa modal mobile responsive
- [ ] Make 2fa modal UI pleasing
- [ ] Write tests

Notifications?
Yes (SMS OTP, Email OTP)

**Comment by datgerhardt** [comment]
The otp modal should be it be place in the @common/component or make as a page

**Comment by adzamkomladev** [comment]
> The otp modal should be it be place in the @common/component or make as a page

component
